name: Delete Environment

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  env_info:
    uses: ./.github/workflows/env_info.yml
    secrets: inherit

  delete_env:
    name: Delete Environment
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.event.ref_type == 'branch') && needs.env_info.outputs.exists == 'true'
    needs: env_info
    environment:
      name: ${{ needs.env_info.outputs.type }}

    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Fidalgo CLI Extension
        run: az extension add -s ${{ needs.env_config.outputs.fidalgo }} -y

      - name: Delete Environment
        run: |
          az fidalgo admin environment delete -g ${{ secrets.PROJECT_RESOURCE_GROUP }} --project-name ${{ secrets.PROJECT_NAME }} -n ${{ needs.env_config.outputs.name }}
