name: Delete Environment

on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  env_info:
    uses: ./.github/workflows/env_info.yml
    secrets: inherit

  delete_env:
    name: Delete Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    needs: env_info
    environment:
      name: ${{ needs.env_info.outputs.type }}

    steps:
      - run: echo "- ${{ needs.env_info.outputs.name }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "- ${{ needs.env_info.outputs.type }}" >> $GITHUB_STEP_SUMMARY
