name: Delete Environment

on:
  delete:
  pull_request:
    types: [closed]

jobs:
  env_config:
    uses: ./.github/workflows/env_config.yml
    secrets: inherit

  delete_env:
    name: Delete Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'
    needs: env_config
    environment:
      name: ${{ needs.env_config.outputs.type }}

    steps:
      - run: echo "- ${{ needs.env_config.outputs.name }}" >> $GITHUB_STEP_SUMMARY
      - run: echo "- ${{ needs.env_config.outputs.type }}" >> $GITHUB_STEP_SUMMARY
