name: Test Environment

on:
  push:
  workflow_dispatch:

jobs:
  parse_yml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/msdev
      - run: cat ./azure.yal
